name: Cache Demo Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-2222ef9

      - name: prime-cache-2222ef9
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" == "true" ]; then
            echo "Cache was restored (HIT)"
          else
            echo "Cache was not found (MISS)"
          fi
